config/routes.rb
Blog::Application.routes.draw do
  
    
    resources :posts
    resources :valids
    resources :sessions, only: [:create, :new] do
      get 'logout', on: :member
    end

  root :to => 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  
  validates_presence_of :title
  validates_presence_of :content
end

app/models/valid.rb
class Valid < ActiveRecord::Base
  attr_accessible :password, :username

  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :login_required
  
  def index
    
    query = params[:query]
    if query.present?
      @posts = Post.where("lower(title) like ?", "%#{query}%")
      p = Post.where("lower(title) like ?", "%#{query}%")
      
      if p.present?
        flash[:notice] = "SUCCESSFULLY FOR FOUND"
      else
        flash[:notice] = "NOT FOUND"
      end

    else
      @posts = Post.order("created_at ASC")
      # flash[:notice] = "YOU MUST ENTERED VALUE"
    end

  end

  def new
    @post = Post.new
  end 

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |f|
      if @post.update_attributes(params[:post])
        f.html  { redirect_to(@post) }
        flash[:notice] = "POST UPDATED"
      else
      end
    end
    
  end

  def show
     @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:notice] = "NEW POST ADDED"
      redirect_to posts_url
    else
      render :new
    end
  end

  def destroy
     @post = Post.find(params[:id])
     @post.destroy
     redirect_to posts_url
  end

  private
    def login_required

      if session[:user_id].present?
        flash[:notice] = "LOGGED"
        # redirect_to posts_path
      else
        flash[:error] = "YOU MUST BE LOGIN !"
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	     
      un = params[:un]
      pass = params[:pass]

      u = Valid.where("username=? AND password=?", un, pass).first
      
      if u.present?
        session[:user_id] = u.id
        
        flash[:notice] = "SUCCESSFULLY"
        redirect_to posts_url
      else
        flash[:notice] = "INVALID LOGIN !"
        render :new
      end
	end

	def logout
		session[:user_id] = nil
		reset_session
		render :new

    flash[:notice] = "SUCCESSFULLY LOG OUT" if session[:user_id] == nil
	end

  before_filter :login_required, only: [:logout]
  def login_required

    if session[:user_id].present?
      flash[:notice] = "SOMEONE IS LOGGED"
      # redirect_to posts_path
    else
      flash[:error] = "YOU MUST BE LOGIN !"
      render :new
    end
  end

  # def logged_in?
  #   if Valid.find(session[:user_id])
  # end

  # def current_user
  #   @current_user = nil
  #   @current_user = (Valid.find(session[:user_id]) if session[:user_id])
  # end

  # before_filter :login_required

  # def login_required 
    
  #   unless (session[:user_id] == nil)

  #     flash[:notice] = "YOU MUST BE LOGGED IN TO VIEW THIS PAGE !"
  #     render :new
    
  #   end
  # end
    # if request.post?
    #   if [authentication code]
    #     if user.activated? 
    #       session[:user_id] = user.id
    #       if params[:route]
    #         redirect_to "#{params[:route]}"
    #       else
    #         redirect_to :controller => 'home'
    #       end
    #     else
    #       flash[:notice] = "Your account hasn't been activated yet.  Check your emails!"
    #     end
    #   else
    #     flash[:notice] = "Invalid email/password combination"
    #   end
    # end

  

	#========================================================================

	# def current_user
 #    	return unless session[:user_id]
 #    	@current_user ||= User.find_by_id(session[:user_id]) 
 #  	end

 #  	def authenticate
 #    	logged_in? ? true : access_denied
 #  	end

	# def logged_in?
 #    	current_user.is_a? User
 #  	end

  # def access_denied
  #  	if session[:user_id] == nil
  #      flash[:notice] = "You must log in to perform this action."
  #      redirect_to root_path
  #   else
  #       flash[:notice] = "#{session[:user_id]} logged."
  #   end

    #   		format.html do
    #     		flash[:alert] = "You must log in to peform this action."
    #     		redirect_to root_path
    #   		end

    #   		format.js do
    #     		render_to_facebox(:partial => 'sessions/login_box')
    #   		end
    # 	end
    # false
  # end
end

app/controllers/valids_controller.rb
class ValidsController < ApplicationController
  
   
  def index
    @valids = Valid.order("created_at ASC")
  end

  def create
   	@valid = Valid.new(params[:valid])
    if @valid.save
      flash[:notice] = "NEW USER ADDED"
      redirect_to valids_url
    else
      flash[:notice] = "YOU MUST ENTER THE VALUE !!!"
      redirect_to new_session_url
    end   
  end
  
  def destroy
     @valid = Valid.find(params[:id])
     @valid.destroy
     redirect_to valids_url
  end
end

#===============================================================================

    

  # def logged_in?
  #   session[:user_id].present?
  # end
  
  # def current_user
  #   @current_user ||= User.find(session[:user_id])
  # end
  
  # def require_user
  #   unless current_user
  #     store_location
  #     flash[:notice] = "You must be logged in to view this page"
  #     redirect_to new_session_url
  #     return false
  #   end
  # end
  
  # def store_location
  #   session[:return_to] = request.request_uri
  # end
 
  # def redirect_back_or_default(default)
  #   redirect_to(session[:return_to] || default)
  #   session[:return_to] = nil
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/valids_helper.rb
module ValidsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<DIV style= "position: center;"><h1>EDITING POST</h1></DIV>				

<%= form_for @post do |f| %>

<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :content %><br/>
	<%= f.text_area :content %>
</p>
<p>
	<%= f.submit 'Update' %>
</p>
	<% end %>


<%= link_to 'POST HISTORY', posts_path %>
<%= link_to 'BACK', posts_path %>

app/views/posts/index.html.erb
<%= image_tag("rails.png") %>

<h1>ARE YOU WANT INPUT POST?</h1>

  <%= form_tag posts_path, method: :get do %>
    <%= text_field_tag :query %>
    <%= submit_tag 'search' %>
  <% end %>
</br>

  <table border="2" width= "500px">
    <tr>
      <th>*</th>
      <th>Title</th>
      <th>Content</th>
    </tr>
   
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </table>
 <br></br>

<%= link_to 'NEW POST', new_post_path %> |
<%= link_to 'LOGOUT', logout_session_path(1) %>

<br></br>

<%= flash[:notice] %>
<%= flash[:error] %>

app/views/posts/new.html.erb
<h1>CREATE POST</h1>

	<% if @post.errors.any? %>
		<div id="errorExplanation">
	  		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this record from being saved:</h2>
	  		<ul>
	  			<% @post.errors.full_messages.each do |msg| %>
	    		<li><%= msg %></li>
	  			<% end %>
	  		</ul>
		</div>
	<% end %>
	
	<%= form_for @post do |f|%>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content %><br/>
		<%= f.text_area :content %>
	</p>

	<p>
		<%= f.submit "CREATE" %> |
		<%= link_to "BACK TO POSTS", posts_path %>
	</p>

	<% end %>

<br></br>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.content %>
<br/><br/>

<%= link_to 'BACK TO POSTS', posts_path %>

<br/><br/>
<%= flash[:notice] %>

app/views/valids/index.html.erb
<h1>USERS LIST</h1>

<DIV style=" color: blue; ";>

	<table border="2" width= "400px">
    	<tr>
      		<th>username</th>
      		<th>password</th>
          <th></th>
    	</tr>
  
    	<% @valids.each do |valid| %>
      	<tr>
        	<td><%= valid.username %></td>
        	<td><%= valid.password %></td>
        	<td><%= link_to 'remove', valid, confirm: 'Are you sure?', method: :delete %></td>
      	</tr>
    	<% end %>
  </table> 	

    <br/><br/>
    <%= link_to "BACK", new_session_path %>

</DIV>
<br/><br/>
<DIV style = "color: green;";><%= flash[:notice]%></DIV>